#define MAX_CMD_LINE_LENGTH 256
#define MAX_TOKENS_ON_A_LINE 30

#define NUMBER_OF_COMMANDS 7

#define HALT 50
#define STATUS 51
#define TIME_CLICK 52
#define CREATE_DEVICE 61
#define CREATE_EVENT 62
#define SET_DEVICE_VALUE 71
#define PROCESS_EVENTS 53

#define UNDEFINED_COMMAND 99

